### ISSUE TITLE
NoBindingError in Chrome

### ISSUE THREAD

**Issue by aciccarello** [angular-in-action/stock-tracker#1]
I am unable to get the application to display correctly due to a JavaScript error. The header displays but in the console there is the following error.

> Uncaught (in promise) 
> application_common.js:273
> 
> "Error: DI Exception
>     at NoBindingError.BaseException (http://localhost:8080/lib/angular2/src/facade/lang.js:24:23)
>     at NoBindingError.AbstractBindingError (http://localhost:8080/lib/angular2/src/di/exceptions.js:38:16)
>     at new NoBindingError (http://localhost:8080/lib/angular2/src/di/exceptions.js:65:16)
>     at Injector._throwOrNull (http://localhost:8080/lib/angular2/src/di/injector.js:653:19)
>     at Injector._getByKeyDefault (http://localhost:8080/lib/angular2/src/di/injector.js:700:21)
>     at Injector._getByKey (http://localhost:8080/lib/angular2/src/di/injector.js:645:25)
>     at Injector._getByDependency (http://localhost:8080/lib/angular2/src/di/injector.js:631:25)
>     at Injector._new (http://localhost:8080/lib/angular2/src/di/injector.js:523:66)
>     at InjectorInlineStrategy.instantiateBinding (http://localhost:8080/lib/angular2/src/di/injector.js:180:30)
>     at ElementInjectorInlineStrategy.hydrate (http://localhost:8080/lib/angular2/src/core/compiler/element_injector.js:785:24)"

**Comment by gnomeontherun** [comment]
I didn't lock down the versions with NPM, but I suspect that it has to do with angular2 being updated. Try to install the exact versions of the dependencies (remove the ^ from the version numbers in package.json, and do `npm install` again), and see if that helps.

**Comment by aciccarello** [comment]
Great, that seemed to do the trick
