### ISSUE TITLE
Red/green color issue when managing stock list

### ISSUE THREAD

**Issue by aciccarello** [angular-in-action/stock-tracker#2]
When managing the visible stock list, the red/green color of the stocks isn't always correct. It appears that this is because the old `increase` or `decrease` class is not being removed from the component.

**Comment by gnomeontherun** [comment]
Thanks, good catch. It seems only when you use the object approach like `[class]={increase: method()}` does it add and subtract the class names. Otherwise, it just adds it. Will commit a fix shortly.
